import "./global.css";

import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";

import { Header } from "@/app/components/header";
import { Main } from "@/app/components/main";
import { css } from "@styled-system/css";
import { Footer } from "./components/footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${poppins.variable} ${body}`}>
        <Header />
        <Main>{children}</Main>
        <Footer />
      </body>
    </html>
  );
}

const body = css({
  minH: "screen",
  display: "flex",
  flexDir: "column",
  bg: "background",
  color: "text",
});
